### ISSUE TITLE
Ошибка при включении модуля

### ISSUE THREAD

**Issue by PaulAsfalt** [servekon/drupal7_email_subscribe#3]
Скачал с гитхаба модуль, но после включения появляется сообщение. "На сайте произошла непредвиденная ошибка. Пожалуйста, повторите попытку позже."

Сотни раз на Drupal добавлял модули, но такое впервые.
В чем может быть дело?

**Comment by servekon** [comment]
Сейчас сам скачал и установил без проблем. Может уже до этого пытались установить этот модуль(подозреваю, что могли остаться таблицы и при повторной установке он ругается на их существование)? В журнале есть записи об ошибке?

**Comment by PaulAsfalt** [comment]
я на работе дважды на разных сайтах на локалке пытался установить. Там у меня показ ошибок отключен, забыл.
Пришел домой, ещё раз попытался.

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'datechange': CREATE TABLE {email_subscribe_users} ( `sid` BIGINT NOT NULL auto_increment COMMENT 'Field ID', `email` VARCHAR(99) NULL DEFAULT NULL COMMENT 'User email', `status` SMALLINT NOT NULL DEFAULT 0 COMMENT '0-Not signed, 1-Subscribe, but email not confirm, 2-Subscribe, 3-Unsubscribe', `uid` INT unsigned NOT NULL DEFAULT 0 COMMENT 'User ID performed an action', `subs_token` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Token for confirm email(md5)', `unsubs_token` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Token to confirm unsubscribe(md5)', `date_subscribe` DATETIME NULL DEFAULT NULL COMMENT 'Date of when user confirm subscribe', `date_unsubscribe` DATETIME NULL DEFAULT NULL COMMENT 'Date of when user confirm unsubscribe', `date_resubscribe` DATETIME NULL DEFAULT NULL COMMENT 'Date of when user confirm re-subscribe', `datechange` TIMESTAMP NOT NULL COMMENT 'Date of change', PRIMARY KEY (`sid`), INDEX `email` (`email`), INDEX `status` (`status`) ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8; Array ( ) in db_create_table() (line 2720 of D:\www\kickstart\includes\database\database.inc).

Не знаю, что я не так делаю.

**Comment by servekon** [comment]
Я под Windows не проверял, но он почему то не может проставлять значения по умолчанию для поля datechange. Залил сейчас коммит. Обновите файл email_subscribe.install. Должно заработать.

**Comment by servekon** [comment]
Позже буду разбираться в чем проблема. Сейчас пока это поле заполняться не будет.

**Comment by PaulAsfalt** [comment]
Включился модуль.
