### ISSUE TITLE
Отправка кучи писем, вместо одного

### ISSUE THREAD

**Issue by Natalia-Ch** [servekon/drupal7_email_subscribe#4]
Если появилось десять новых материалов в течении интервала отправки писем, то юзер получит десять писем. Можно ли сделать, чтобы юзер получал одно письмо с десятью  ссылками в нем? Это было бы правильнее, на мой взгляд..

**Comment by servekon** [comment]
Здравствуйте. Вы не первый человек, который просит эту возможность. Я её уже начал разрабатывать, но всё никак не хватает свободного времени, чтобы доделать. Постараюсь реализовать как можно скорее.

**Comment by Natalia-Ch** [comment]
Постарайтесь, пожалуйста! Потому что для задачи простой рассылки уведомлений о новых материалах ваш модуль подходит как нельзя лучше! С монстрами типа  simlpenews одна головная боль :(

**Comment by servekon** [comment]
Проделал достаточно много работы. Обновил модуль до версии 1.0.4. Основные изменения - возможность группировать материалы в одном письме. Но для этого нужно будет переделать шаблон "Сообщение о появлении нового контента".
